### ISSUE TITLE
Latest version of Mondo is not loaded

### ISSUE THREAD

**Issue by twhetzel** [monarch-initiative/ontotools-docker#7]
Following the latest updates to the Monarch OLS instance (), the GitHub Action was manually triggered and the ontology was reviewed. The latest changes to "mondo-edit.obo" in `master` are _not_ displayed in Monarch OLS. For example, see the Mondo term here: https://ols.monarchinitiative.org/ontologies/mondo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FMONDO_0004759 should have been re-labeled ([PR](https://github.com/monarch-initiative/mondo/pull/6922)).

I did check mondo-edit in Protege from the latest pull from `master` and the term does display as being re-labeled.

Currently assigning to @matentzn in case this is an issue with how the ontology is being built.

cc: @falquaddoomi

**Comment by twhetzel** [comment]
Thanks @falquaddoomi. I see you mentioned `main`, but the ontology mondo is still using `master` - is that important? I've been going through the files and don't see an obvious place where that makes a difference.

**Comment by matentzn** [comment]
@falquaddoomi Can we get proof that the latest redeploy run did actually ran the `make` pipeline?

**Comment by falquaddoomi** [comment]
> @falquaddoomi Can we get proof that the latest redeploy run did actually ran the `make` pipeline?

It requires access to the `ontotools-stack` VM, but you can check the latest logs from the run in this folder: `/var/checkouts/ontotools-docker/deploy_logs`. I just checked the latest log (`deploy_20231129_205303_stdout.log`), and it appeared to run `make` as evidenced by this line at the beginning of the log: `make: Nothing to be done for 'ontologies'.`. I ran the redeploy script several times before that most recent run, so that's likely why it's saying there's nothing to be done, but it's evidence that `make` ran at least.

Also, to clarify, the GitHub Action is invoking `pull_and_redeploy.sh` one these lines, https://github.com/monarch-initiative/ontotools-docker/blob/master/.github/workflows/redeploy.yaml#L40-L41. `pull_and_redeploy.sh` simply invokes `redeploy.sh`, so anything in that script is being run, as far as I can tell.

This might be a good time to bring up that the OLS indexer's output is *extremely* verbose; the stdout logs are ~170MB in size, and significantly impact the runtime if they're written to the screen, and likely are impacting performance being written to a file. While debugging this months ago I'd created a custom version of the indexer that reduces the log verbosity, but I wasn't sure how to get that submitted or if it was even desirable.

**Comment by twhetzel** [comment]
I manually ran the GH Action workflow and there was an error:
```
[update-gcp-services](https://github.com/monarch-initiative/ontotools-docker/actions/runs/7052670406/job/19198217811#step:2:20)
The "create_credentials_file" option is true, but the current GitHub workspace is empty. Did you forget to use "actions/checkout" before this step? If you do not intend to share authentication with future steps in this job, set "create_credentials_file" to false.
```

**Comment by falquaddoomi** [comment]
Just to keep you all posted, I checked the permissions in the `.git` folder and there were in fact a few files that were not group-writeable. I've changed the ownership of the `.git` folder to the user account that performs the runs (`ols_deployer`) and I've made all the subfolders of the `.git` folder retain group ownership values, which should hopefully mitigate the problem going forward.


As a heads up, If the "Git pull master and launch redeploy.sh" step fails and you see output like the following, then it's the Git permissions issue again:

```
remote: Compressing objects: 100% (4/4), done.        
remote: Total 4 (delta 2), reused 0 (delta 0), pack-reused 0        
Unpacking objects:  25% (1/4)   
Unpacking objects:  50% (2/4)   
error: insufficient permission for adding an object to repository database .git/objects
fatal: failed to write object
fatal: unpack-objects failed
```

**Comment by twhetzel** [comment]
From a few checks, it looks good to me! The re-labelled term, zoophilia, now shows up as displayed with this as the label and the ontology metadata shows as "Version IRI: [ http://purl.obolibrary.org/obo/mondo/releases/2023-11-30/mondo.owl](http://purl.obolibrary.org/obo/mondo/releases/2023-11-30/mondo.owl)" so I'll close this ticket and ask Sabrina and Nicole to also take a look. Thanks all!
